### ISSUE TITLE
Versions of SQL Server to Support

### ISSUE THREAD

**Issue by FlipperPA** [FlipperPA/django-mssql-backend#3]
This link provides a summary of Microsoft's SQL Server support cycle:
http://www.mirazon.com/a-comprehensive-guide-to-microsoft-end-of-support/

Since SQL Server 2008 (and R2) are both now out of extended support, I suggest we start by targeting support for SQL Server 2012 and above.

This will allow us to only support the new field types introduced in SQL Server 2008, such as `DATE` and `DATETIME2`.

**Comment by daybarr** [comment]
https://support.microsoft.com/en-gb/lifecycle/search/1044 is a primary source for EOL dates from Microsoft themselves and confirms that SQL Server 2008 and R2 are out of support.

> This will allow us to only support the new field types introduced in SQL Server 2008, such as `DATE` and `DATETIME2`.

What exactly does "**only** support" mean? Would there be a plan to support pre-existing SQL Server databases that have `DATETIME` fields? Perhaps ones created using Django with `django-pyodbc-azure` (or one of its predecessors) back when that was the default type used for a `DateTimeField`? Or would existing Django projects have to add a migration, possibly using raw SQL, in order to change existing field types in already deployed databases so that they can continue to work with this backend?

Thanks

**Comment by FlipperPA** [comment]
@daybarr That's an excellent point. We'll have to balance backwards compatibility with whatever decision the community comes to consensus on with regards to potential support for timezones. I honestly don't have enough information on how many people this would impact. I also don't know whether changing the mapping to be exclusively DATETIME2 would cause Django to automatically create and `ALTER TABLE ALTER COLUMN` migration. Time for some testing. Thanks for the feedback!

**Comment by mrbean-bremen** [comment]
As a side note: I had to change the data type from `DATETIME` to `DATETIME2` in a db upgrade some time ago, and I basically did this by using a series of SQL commands like
```ALTER TABLE dbo.<table_name> ALTER COLUMN <columnName> datetime2```,
which worked without a problem - so I guess this could be automated in a migration.
